<?php

return [
    //Operation failed
    '001999' => 'no information for the bank yet',
    '001001' => 'The wallet balance doesn’t allow to process transaction',
    '001002' => 'The user ID used as Author has to be the wallet owner',
    '001011' => 'Transaction amount is higher than maximum permitted amount',
    '001012' => 'Transaction amount is lower than minimum permitted amount',
    '001013' => 'Invalid transaction amount',
    '001014' => 'CreditedFunds must be more than 0 (DebitedFunds can not equal Fees)',
    //PayIn Web errors
    '001030' => 'The user never gets the payment page and never opens the Payline session',
    '001031' => 'The User clicks on "Cancelled" on the payment page',
    '101002' => 'The User clicks on "Cancelled" on the payment page',
    '001032' => 'The user is still on the payment page (Payline session)',
    '001033' => 'The session has expired so the Payin Web is failed. The user has gone on the payment page',
    '001034' => 'The user went to the payment page but let the session expired. So the Payin Web has failed',
    '101001' => 'The user does not complete transaction',
    '0000000000' => '3d secure cards are not allowed please use master/visa',
    //Refund transaction errors
    '001401' => 'Transaction has already been successfully refunded',
    '005403' => 'The refund cannot exceed initial transaction amount',
    '005404' => 'The refunded fees cannot exceed initial fee amount',
    '005405' => 'Balance of client fee wallet insufficient',
    '005407' => 'Duplicated operation: you cannot refund the same amount more than once for a transaction during the same day',
    //Card input errors
    '105101' => 'Invalid card number',
    '105102' => 'The card holder name given doesn’t match the real owner of the card',
    '105103' => 'Invalid PIN code',
    '105104' => 'Invalid PIN format',
    //Token Input errors
    '105299' => 'There was a too long time between the card registration request and the first action done with this card',
    '105202' => 'This error is returned in case the card number formate is wrong (on card registration)',
    '105203' => 'This error is returned in case the expiry date is wrong (on card registration)',
    '105204' => 'This error is returned in case the CVV is wrong (on card registration)',
    '105205' => 'This error is returned in case the ReturnURL is wrong on CardRegistration process',
    '105206' => 'Registration data : Invalid format',
    //Transaction Refused
    '101101' => 'Transaction refused by the bank (Do not honor)',
    '101102' => 'Transaction refused by the bank (Amount limit)',
    '101103' => 'Transaction refused by the terminal',
    '101104' => 'Transaction refused by the bank (card limit reached)',
    '101105' => 'The card has expired',
    '101106' => 'The card has not been well registrated in Mangopay or the first operation (pre-authorisation or Payin) has failed. So not it is unusable',
    '101410' => 'The card has not been disabled on Mangopay and is no longer useable',
    '101111' => 'Too much attempts for the same transaction',
    '101112' => 'This is a card limitation on spent amount',
    '101113' => 'Maximum attempts with this cards reached. You must try again after 24 hours',
    '101115' => 'This is a card limitation on spent amount',
    '101116' => 'The contribution transaction has failed',
    '101199' => 'The transaction has been refused by the bank. Contact your bank in order to have more information about it',
    //Secure mode / 3DSecure errors
    '101399' => 'Secure mode: 3DSecure authentication is not available',
    '101304' => 'Secure mode: The 3DSecure authentication session has expired',
    '101303' => 'Secure mode: The card is not compatible with 3DSecure',
    '101302' => 'Secure mode: The card is not enrolled with 3DSecure',
    '101301' => 'Secure mode: 3DSecure authentication has failed',
    //Tokenization / Card registration errors
    '001599' => 'The token has not been created',
    //KYC errors
    '002999' => 'Blocked due to a Debited User’s KYC limitations (maximum debited or credited amount reached)',
    '002998' => 'Blocked due to the Bank Account Owner’s KYC limitations (maximum debited or credited amount reached)',
    //Fraud issue
    '008999' => 'Fraud policy error',
    '008001' => 'Counterfeit Card',
    '008002' => 'Lost Card',
    '008003' => 'Stolen Card',
    '008004' => 'Card bin not authorized',
    '008005' => 'Security violation',
    '008006' => 'Fraud suspected by the bank',
    '008007' => 'Opposition on bank account (Temporary)',
    '008500' => 'Transaction blocked by Fraud Policy',
    '008600' => 'Wallet blocked by Fraud policy',
    '008700' => 'User blocked by Fraud policy 	',
    //Technical errors
    '009103' => 'PSP configuration error',
    '009199' => 'PSP technical error',
    '009499' => 'Bank technical error',
    '009999' => 'Technical error',
    '009101' => 'PSP timeout please try later',
    //Tokenization server error codes
    '02101' => 'Internal Error',
    '02632' => 'Method GET is not allowed',
    '09101' => 'Username/Password is incorrect',
    '09102' => 'Account is locked or inactive',
    '01902' => 'This card is not active',
    '02624' => 'Card expired',
    '09104' => 'Client certificate is disabled',
    '09201' => 'You do not have permissions to make this API call',
    '02631' => 'Delay exceeded',
    //Tokenization server error codes (while card registration)
    '02625' => 'Invalid card number',
    '02626' => 'Invalid date. Use mmdd format 	',
    '02627' => 'Invalid CCV number',
    '02628' => 'Transaction refused',
    //Payout error codes
    '121999' => 'Generic withdrawal error',
    '121001' => 'The bank wire has been refused',
    '121002' => 'The author is not the wallet owner',
    '121003' => 'Insufficient wallet balance',
    '001001' => 'Insufficient wallet balance',
    '121004' => 'Specific case: please contact our Support Team or Other case',
    '121005' => 'Refused due to the Fraud Policy',
    '002998' => 'Blocked due to the Bank Account Owner’s KYC limitations (maximum debited or credited amount reached',
    '002999' => 'Blocked due to a Debited User’s KYC limitations (maximum debited or credited amount reached)',
        /* '001012' => '',
          '001013' => '',
          '001002' => '',
          '001011' => '',
          '001012' => '',
          '001013' => '',
          '001002' => '',
          '001011' => '',
          '001012' => '',
          '001013' => '', */
];

